### ISSUE TITLE
Can't find code for creating Prob attribute

### ISSUE THREAD

**Issue by OliveMY** [bald6354/edncnn#1]
Hi,
I'm trying to reproduce the process of creating the train/test data of your model. However it seems the code is incomplete. For example, I can't find code for creating aedat.data.polarity.Prob attribute.
Would you mind providing a .m file containing such process?

**Comment by bald6354** [comment]
Check mainScript.m line 152-160

**Comment by bald6354** [comment]
If you still have issues let me know
